### ISSUE TITLE
Suggestion: Thing types and flags

### ISSUE THREAD

**Issue by sttng** [ehaliewicz/Manifold#1]
https://github.com/ehaliewicz/PortalView/blob/bb08cd0490c9defb1b5ed93517fd59f3221d1f88/src/python/wad.py#L326

Doom (incl. Doom2 and Final Doom) uses 123 thing types, so 1 byte is sufficient.
Source: https://doomwiki.org/wiki/Thing_types#Doom.2C_Doom_II.2C_Final_Doom

You can also "move" one of the flags to the thing types if you use singed numbers for thing types. Then store the remaining flags in 1 byte.

Example:
* flag bit 4: Thing is not in single player 

Drop it from flags and implement as a negative in type number.
* Bagpack Type No.  8 -> -8 (this backpack isn't available in multiplier)

Thats in case the multiplayer flag needs to be kept at all.

**Comment by ehaliewicz** [comment]
Thanks for the first issue/suggestion on this repo.  I agree that it's unlikely I'll ever have more object types supported than doom.  I don't know if this engine will ever support multiplayer, but the negative number trick is interesting.
